spring:
  datasource:
    url: jdbc:mysql://172.18.0.1:3306/db_security
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#120000 = 2 minutes
#300000 = 5 minutes
jwt:
  expiration-token: 120000
  expiration-refresh-token: 300000
  secret: d41d8cd98f00b204e9800998ecf8427e